repos:
  # --- Secret scanning ---
  - repo: local
    hooks:
      - id: gitleaks-staged
        name: Gitleaks (staged)
        entry: gitleaks protect --staged --redact
        language: system
        pass_filenames: false

      # Prettier (Node-based, no archived mirrors)
      - id: prettier
        name: Prettier (YAML/JSON/Markdown)
        language: node
        entry: prettier
        args: [--ignore-unknown, --write]
        additional_dependencies: ["prettier@3.3.3"]
        types_or: [yaml, json, markdown]

      - id: block-terraform-artifacts
        name: Block Terraform artifacts (.tfstate, .tfplan, tf.json, .terraform/)
        language: fail
        entry: "Do not commit Terraform state/plan artifacts."
        files: >
          (?x)
          (^|/)
          (
            terraform\.tfstate(\.backup)?      |
            .*\.tfstate(\..*)?                 |
            .*\.tfplan                         |
            tf\.plan                           |
            tf\.json                           |
            \.terraform/.*
          )

  # --- Terraform format & validate ---
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
        args:
          - --hook-config=--tf-init-args=-backend=false

  # --- Helpful hygiene checks ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-yaml
