name: Deploy Terraform (apply)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_API1 }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        working-directory: Landing-Zone
        run: terraform init

      - name: Terraform Apply
        working-directory: Landing-Zone
        run: terraform apply -auto-approve


      - name: Cleanup secrets (best-effort)
        if: always()
        shell: bash
        run: |
          # Overwrite for subsequent steps in this job
          echo "TF_TOKEN_app_terraform_io=" >> "$GITHUB_ENV"
          unset TF_TOKEN_app_terraform_io || true
          # Remove any TF CLI creds file if a previous action created one
          rm -f "$HOME/.terraformrc" "$HOME/.terraform.d/credentials.tfrc.json" || true
          # Clean local TF artifacts from workspace
          rm -rf "${GITHUB_WORKSPACE}/Landing-Zone/.terraform" \
                 "${GITHUB_WORKSPACE}/Landing-Zone/.terraform.lock.hcl" || true
