name: Deploy Terraform (apply)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    # ... (previous steps for checkout, node, terraform are correct) ...
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    # - name: Configure Terraform Cloud Credentials
    #   run: |
    #     cat <<-EOF > ~/.terraformrc
    #     credentials "app.terraform.io" {
    #       token = "${{ secrets.TF_API_TOKEN }}"
    #     }
    #     EOF

    - name: Terraform Init
      working-directory: Landing-Zone
      run: terraform init

    - name: Terraform Apply
      working-directory: Landing-Zone
      run: terraform apply -auto-approve
